### ISSUE TITLE
correct way to enforce suggested parameter type?

### ISSUE THREAD

**Issue by 152334H** [google/vizier#1185]
```python
from vizier.service import clients
from vizier.service import pyvizier as vz

study_config = vz.StudyConfig()
study_config.search_space.root.add_int_param('x', -2, 2)
study = clients.Study.from_study_config(study_config, owner='o', study_id='i')
print(study.suggest(count=1)[0].parameters)
```

`INTEGER` parameters, when suggested by a Study, output `float`s and not `int`s:

```bash
$ python a.py
WARNING:absl:Python 3.8+ is required in this case.
{'x': 0.0}
```

Is it the responsibility of the end user to correctly cast suggested parameters to the correct type? Or is this unexpected behavior?

**Comment by xingyousong** [comment]
This is due to the conversion from proto to Python object: https://github.com/google/vizier/blob/main/vizier/_src/pyvizier/oss/proto_converters.py#L328-L341

Unfortunately the `google.protobuf.Value` only has a "numeric" field being a float type, which is used for both DOUBLE and INT parameters: https://github.com/google/vizier/blob/main/vizier/_src/service/study.proto#L102

It's not easy for us to forcibly change the values to the right types, maybe we can do it later. For now let's assume the user needs to e.g. explicitly call `int(value)` themselves.
