### ISSUE TITLE
Suggestions duplicates for Grid Search, limiting suggestions

### ISSUE THREAD

**Issue by niemiaszek** [google/vizier#1216]
Another issue I've met setting up Vizier OSS for myself. This one actually includes code example for #1215, with `ray` for single/multi-node setup, but can be simplified to use `joblib` for multi-core case.

I started with some simple grid search problem, which I previously setup myself straight from `itertools.product` and some post-processing to remove cases, which I mark as `infeasible` with Vizier.
```python

def main():
    ray.init(address="auto")

    problem = vz.ProblemStatement()
    problem.search_space.root.add_discrete_param(
        name="safe_zone", feasible_values=[0.0, 0.25, 0.5], scale_type=vz.ScaleType.UNIFORM_DISCRETE
    )
    problem.search_space.root.add_discrete_param(
        name="vad_gatekeeping", feasible_values=[0.1, 0.25, 0.5], scale_type=vz.ScaleType.UNIFORM_DISCRETE
    )
    problem.search_space.root.add_discrete_param(
        name="vad_threshold", feasible_values=[0.05, 0.08, 0.12], scale_type=vz.ScaleType.UNIFORM_DISCRETE
    )
    problem.search_space.root.add_discrete_param(
        name="chunk_size", feasible_values=[1, 2, 3, 4], scale_type=vz.ScaleType.UNIFORM_DISCRETE
    )
    problem.search_space.root.add_discrete_param(
        name="gender_audio_frame", feasible_values=[1, 2, 4], scale_type=vz.ScaleType.UNIFORM_DISCRETE
    )
    problem.search_space.root.add_discrete_param(
        name="vad_audio_frame", feasible_values=[1, 2, 4], scale_type=vz.ScaleType.UNIFORM_DISCRETE
    )
    problem.metric_information.append(vz.MetricInformation(name="total_accuracy", goal=vz.ObjectiveMetricGoal.MAXIMIZE))

    study_config = vz.StudyConfig.from_problem(problem)
    study_config.algorithm = "GRID_SEARCH"

    server = servers.DefaultVizierServer(server_ip)
    clients.environment_variables.server_endpoint = server.endpoint
    print(clients.environment_variables.server_endpoint)
    study_client = clients.Study.from_study_config(study_config, owner="x", study_id="example_grid_search")

    print("Local SQL database file located at: ", service.VIZIER_DB_PATH)

    runners = [
        experiment_runnner.remote(study_client.resource_name, server.endpoint)
        for runner in range(int(ray.ray.available_resources()["CPU"] - 1))
    ]
    [ray.get(runner) for runner in runners]  # wait for the runners to be done with their job

    for optimal_trial in study_client.optimal_trials():
        optimal_trial = optimal_trial.materialize()
        print("Optimal Trial Suggestion and Objective:", optimal_trial.parameters, optimal_trial.final_measurement)


@ray.remote(num_cpus=1)
def experiment_runnner(resource_name: str, endpoint: str):
    clients.environment_variables.server_endpoint = endpoint
    study_client = clients.Study.from_resource_name(resource_name)
    unique_client_id = str(uuid.uuid4())

    while suggestions := study_client.suggest(count=1, client_id=unique_client_id):
        suggestion = suggestions[0]

        # Infeasibilitiy
        if suggestion.parameters["chunk_size"] > suggestion.parameters["gender_audio_frame"]:
            suggestion.complete(vz.Measurement(), infeasible_reason="chunk_size > gender_frame")
            continue
        if suggestion.parameters["gender_audio_frame"] > suggestion.parameters["vad_audio_frame"]:
            suggestion.complete(vz.Measurement(), infeasible_reason="gender_audio_frame > vad_audio_frame")
            continue
        
        actual_evaluation() # skipping the code used for evaluation
        final_measurement = vz.Measurement({"total_accuracy": objective["total_accuracy"]})
        suggestion.complete(final_measurement)
```
For this code, it's clear that there are 972 configurations to try. 297 of them will be feasible.

When checked, I got 972 unique parameters configurations as intended, with 297 of them resulting in not None metric. However, the problem is that I'm already on 6819 succeeded trials and 16643 skipped by infeasibility, which indicates that suggestions are somehow looping. I would expect grid search designer to go over possible cases and then start suggesting Nones. 

Also, is it possible to filter for only succeeded trials (completed without infeasibility)? `vz.TrialStatus` lacks such distinction. 

## Limiting suggestions
Is there any built-in mechanism for limiting suggestions? I would expect something like this exist for the service. `max_num_trials` is also mentioned for `VizierClient.get_suggestions()`, but I couldn't find anything like this. It's very easy when optimization is done like in docs example (using `range` to get exact number of suggestions), but it's a bit harder in distributed setting. I've seen in paper you mention _Observation Noise_ (B.2) with possible revisiting of suggestions, which makes perfect sense, but it's not really useful for my grid search example and I would expect suggestions being exhausted.

Thanks for your time going through the community issues. I know it's a lot and my ideas might seem straight dumb, but I hope these issues could be helpful for OSS Vizier users in the future.

**Comment by xingyousong** [comment]
In-line responses below:

**However, the problem is that I'm already on 6819 succeeded trials and 16643 skipped by infeasibility, which indicates that suggestions are somehow looping. I would expect grid search designer to go over possible cases and then start suggesting Nones.**
  * Since the search space only has 972 possible configurations, the grid designer would loop back, as expected. Its behavior is basically keeping track of a [`current_index`](https://github.com/google/vizier/blob/main/vizier/_src/algorithms/designers/grid.py#L49) which keeps track of the number of suggestions made so far, and then proposing new suggestions by taking the modulo of this `current_index` with respect to search space sizes. By design, our algorithms aren't meant to stop.

**Also, is it possible to filter for only succeeded trials (completed without infeasibility)?**
  * You're correct in that `TrialStatus` doesn't have an infeasible field. We consider infeasible trials as still `COMPLETED`, and it's up to the user to decide which ones to filter further. This shouldn't be hard since it'll just be a list comprehension, e.g. `feasible_completed = [t if not t.infeasible for t in all_completed_trials]`

**Is there any built-in mechanism for limiting suggestions?**
  * Can you clarify what you mean - in which context do you need to limit suggestions? `study_client.suggest(count=some_number)` will always output at most `some_number` of suggestions. If you mean wanting the server to stop providing suggestions after some total trial count, we don't support that - it's up to the user to do this stopping. But this should be easy, i.e. you can make a check for the number of trials so far, and then [set the study client's status to completed](https://github.com/google/vizier/blob/main/vizier/_src/service/clients.py#L199).

**Comment by niemiaszek** [comment]
In-line responses below:
**grid designer would loop back, as expected. (...) By design, our algorithms aren't meant to stop.**
* Right, that's expected after looking into source. My initial assumption was that the designer would keep suggesting until finite search space is exhausted.

**This shouldn't be hard since it'll just be a list comprehension**
* Fair point, ended up doing the same

**Can you clarify what you mean - in which context do you need to limit suggestions?**
* I had in mind limiting on the server side. I would expect someone to start optimization with some limited budget (steps/time) in mind. Thanks for explaining, it's indeed easy to do.

This solves all my questions, thanks
